#!/usr/bin/env php
<?php

// Composer autoload.
require __DIR__ . '/vendor/autoload.php';

// Included classes.
use Marks\StockfighterSolution\Application;
use Marks\StockfighterSolution\Levels\ChockABlock;
use Marks\StockfighterSolution\Levels\SellSide;
use Configula\Config;

// Load the configuration.
$config = new Config(__DIR__ . '/config');

// Set the API key.
\Marks\Stockfighter\Stockfighter::setApiKey($config->key);

// Initialize the application.
$application = new Application('Stockfighter Solutions');
$application->setConfig($config);
$application->add(new ChockABlock());
$application->add(new SellSide());
$application->run();

?>
